# This is the config for bunker plugin
# Version 1.2

# Edit the message sent to players went to need command usage
argCommandUsage: "Invalid arguments! Use /bunker [buy/home/visit]"
visitCommandUsage: "Usage: /bunker visit [player]"
# Edit the message sent to the player when using /bunker home
homeMsg: "Teleporting you to your bunker..."
noBunker: "You don't own a bunker. Use /bunker buy to obtain one"
# Edit the message sent to the player when using /bunker visit
playerNotExist: "The player, %player%, you are trying to visit does not exist or have a bunker!"
pendingVisitRequest: "You already have a pending visit request. Please wait for a response."
requestMsg: "%player% is requesting to visit you. You have 60 seconds to accept! %accept% %decline%"
acceptRequest: "%visitor% is visiting your island.."
declineRequest: "You have declined %visitor%'s visit request.."
allowVisit: "%owner% has accepted your visit request!"
declineVisit: "%owner% has been declined your visit request."
# Edit the message sent to the player when using /bunker buy
outOfBunkers: "Fatal error: Out of storage for bunkers. Contact an admin to help you out!"
alreadyPurchased: "You have already purchased a bunker!"
bunkerPurchased: "You have successfully purchased a bunker!"

# Adjust properties of the bunker

# schematics can be found in bunker/schematics, you have to create the folder if it doesn't exist.
schematicName: "bunker.schem"
# Schematic coordinate location
main:
  schematicCoords:
    x: 0
    y: 0
    z: 0
  spawnCoords:
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  npcID: 0
  npcCoords:
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  generatorType: "stone"
  generatorLevel: 1
  generatorCoords:
    x: 0.0
    y: 0.0
    z: 0.0